import Head from 'next/head'
import NavBar from '../components/NavBar'
import PopUp from '../components/PopUp'
import SearchBar from '../components/SearchBar'

export default function Home() {

  console.log(process.env.NEXT_PUBLIC_DUMMYAPI_APP_ID)
  return (
    <>
      <Head>
        <title>Simple Quick</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='background flex'>
        <NavBar />
        <div className="w-full h-full relative">
          <SearchBar />
          <PopUp />
        </div>
      </main>
    </>
  )
}
